version: '2'

services:
  
  web:
    build: httpd
    ports:
      - "80:80"
    volumes:
      - ../app:/usr/local/apache2/htdocs
    links:
      - php

  php:
    build: php
    volumes:
      - ../app:/usr/local/apache2/htdocs
