version: '2'

services:
  
  web:
    build: httpd
    ports:
      - "80:80"
    volumes:
      - ../app:/usr/local/apache2/htdocs
    links:
      - php

  php:
    build: php
    volumes:
      - ../app:/usr/local/apache2/htdocs
    links:
      - mysql

  mysql:
    image: mysql:5.6
    ports:
      - "3306:3306"
    mem_limit: 512M
    environment:
      - MYSQL_ROOT_PASSWORD=root
